[general]
name = "WiFi Temp Sensor ds18b20"
description = "Отправляет в топик `current_temp/pepeunit` значения датчика температуры `ds18b20`"
language = "Micropython"
hardware = ["esp8266", "esp32", "esp32c3", "esp32s3", "ds18b20", "резистор 4.7кОм", "wires"]
firmware = [
  {name = "RELEASE-1.1.1", link = "https://git.pepemoss.com/pepe/pepeunit/libs/pepeunit_micropython_client/-/releases/1.1.1"}
]
stack = ["pepeunit_micropython_client"]
version = "1.1.1"
license = "AGPL v3 License"
authors = [
    {name = "Ivan Serebrennikov", email = "admin@silberworks.com"}
]


[images]
schema = "https://minio.pepemoss.com/public-data/image/wifi_temp_sensor.png"

[physical_io]
"client.settings.PIN_DS18B20" = "Цифровое значение температуры от датчика `ds18b20`"

[env_description]
PIN_DS18B20 = "Номер пина для датчика `ds18b20`"
PUBLISH_SEND_INTERVAL = "Частота публикации данных в `current_temp/pepeunit` в миллисекундах"
PUC_WIFI_SSID = "Имя сети `WiFi`"
PUC_WIFI_PASS = "Пароль от сети `WiFi`"

[topic_assignment]
"current_temp/pepeunit" = "Текущая температура в текстовом формате (например, `27.5`)"

[work_algorithm]
steps = [
  "Подключение к `WiFi`",
  "Подключение к `MQTT` Брокеру",
  "Инициализация датчика `ds18b20`",
  "Каждые `PUBLISH_SEND_INTERVAL` миллисекунд публикуется значение температуры в `current_temp/pepeunit`"
]

[installation]
steps = [
  "Установите образ `Micropython` указанный в `firmware` на `esp8266`, как это сделано в [руководстве](https://micropython.org/download/ESP8266_GENERIC/)",
  "Создайте `Unit` в `Pepeunit`",
  "Установите переменные окружения в `Pepeunit`",
  "Скачайте архив c программой из `Pepeunit`",
  "Распакуйте архив в директорию",
  "Загрузите файлы из директории на физическое устройство, например командой: `ampy -p /dev/ttyUSB0 -b 115200 put ./ .`",
  "Запустить устройство нажатием кнопки `reset`"
]